from __future__ import annotations

from dataclasses import dataclass
import os
import platform
import threading
from typing import Callable, Protocol

from .typing_backend import SOFTWARE_EVENT_MARKER


class InputBlockerError(RuntimeError):
    pass


class InputBlocker(Protocol):
    def start(self) -> None:
        """Prepare low-level keyboard blocking resources."""

    def set_blocking(self, enabled: bool) -> None:
        """Enable or disable user keyboard suppression."""

    def stop(self) -> None:
        """Release low-level resources."""


@dataclass
class NullInputBlocker:
    blocking: bool = False

    def start(self) -> None:
        return None

    def set_blocking(self, enabled: bool) -> None:
        self.blocking = enabled

    def stop(self) -> None:
        self.blocking = False


class MacKeyboardInputBlocker:
    """Suppress user keyboard input while auto typing is running.

    The event tap blocks key events from physical keyboards, but allows events
    generated by this process so the Quartz typing backend can still type.
    Ctrl+2 is handled inside this blocker because normal global hotkeys may be
    suppressed while blocking is active.
    """

    _PAUSE_KEYCODES = {19, 84}  # top-row 2 and keypad 2

    def __init__(self, on_pause: Callable[[], None]) -> None:
        self._on_pause = on_pause
        self._blocking = threading.Event()
        self._ready = threading.Event()
        self._lock = threading.Lock()
        self._thread: threading.Thread | None = None
        self._tap = None
        self._source = None
        self._run_loop = None
        self._quartz = None
        self._start_error: str | None = None

    def start(self) -> None:
        with self._lock:
            if self._thread and self._thread.is_alive():
                return
            self._ready.clear()
            self._start_error = None
            self._thread = threading.Thread(
                target=self._run_event_tap,
                name="MacKeyboardInputBlocker",
                daemon=True,
            )
            self._thread.start()

        if not self._ready.wait(timeout=2.0):
            raise InputBlockerError(
                "Keyboard input blocker did not start. Grant Input Monitoring and Accessibility permissions."
            )
        if self._start_error:
            raise InputBlockerError(self._start_error)

    def set_blocking(self, enabled: bool) -> None:
        if not enabled:
            self._blocking.clear()
            return
        if self._start_error:
            raise InputBlockerError(self._start_error)
        if not self._thread or not self._thread.is_alive():
            self.start()
        self._blocking.set()

    def stop(self) -> None:
        self._blocking.clear()
        quartz = self._quartz
        if quartz is not None and self._run_loop is not None:
            quartz.CFRunLoopStop(self._run_loop)
        thread = self._thread
        if thread and thread.is_alive():
            thread.join(timeout=1.0)

    def _run_event_tap(self) -> None:
        try:
            import Quartz  # type: ignore[import-not-found]

            self._quartz = Quartz
            mask = (
                Quartz.CGEventMaskBit(Quartz.kCGEventKeyDown)
                | Quartz.CGEventMaskBit(Quartz.kCGEventKeyUp)
                | Quartz.CGEventMaskBit(Quartz.kCGEventFlagsChanged)
            )
            self._tap = Quartz.CGEventTapCreate(
                Quartz.kCGSessionEventTap,
                Quartz.kCGHeadInsertEventTap,
                Quartz.kCGEventTapOptionDefault,
                mask,
                self._event_callback,
                None,
            )
            if self._tap is None:
                self._start_error = (
                    "Cannot create macOS keyboard event tap. Grant Input Monitoring and Accessibility permissions."
                )
                self._ready.set()
                return

            self._source = Quartz.CFMachPortCreateRunLoopSource(None, self._tap, 0)
            self._run_loop = Quartz.CFRunLoopGetCurrent()
            Quartz.CFRunLoopAddSource(
                self._run_loop,
                self._source,
                Quartz.kCFRunLoopCommonModes,
            )
            Quartz.CGEventTapEnable(self._tap, True)
            self._ready.set()
            Quartz.CFRunLoopRun()
            Quartz.CGEventTapEnable(self._tap, False)
        except Exception as exc:  # pragma: no cover - platform dependent
            self._start_error = str(exc)
            self._ready.set()

    def _event_callback(self, proxy, event_type, event, refcon):  # noqa: ANN001
        quartz = self._quartz
        if quartz is None:
            return event

        if event_type in {
            quartz.kCGEventTapDisabledByTimeout,
            quartz.kCGEventTapDisabledByUserInput,
        }:
            if self._tap is not None:
                quartz.CGEventTapEnable(self._tap, True)
            return event

        if not self._blocking.is_set():
            return event

        if self._is_software_event(quartz, event):
            return event

        if self._is_pause_hotkey(quartz, event_type, event):
            self._blocking.clear()
            self._on_pause()
            return None

        if event_type in {
            quartz.kCGEventKeyDown,
            quartz.kCGEventKeyUp,
            quartz.kCGEventFlagsChanged,
        }:
            return None
        return event

    def _is_pause_hotkey(self, quartz, event_type, event) -> bool:  # noqa: ANN001
        if event_type != quartz.kCGEventKeyDown:
            return False
        keycode = quartz.CGEventGetIntegerValueField(event, quartz.kCGKeyboardEventKeycode)
        flags = quartz.CGEventGetFlags(event)
        return keycode in self._PAUSE_KEYCODES and bool(flags & quartz.kCGEventFlagMaskControl)

    def _is_software_event(self, quartz, event) -> bool:  # noqa: ANN001
        try:
            marker = quartz.CGEventGetIntegerValueField(event, quartz.kCGEventSourceUserData)
            if marker == SOFTWARE_EVENT_MARKER:
                return True
        except Exception:
            pass

        try:
            pid = quartz.CGEventGetIntegerValueField(event, quartz.kCGEventSourceUnixProcessID)
            return pid == os.getpid()
        except Exception:
            return False


def default_input_blocker(on_pause: Callable[[], None]) -> InputBlocker:
    if platform.system() == "Darwin":
        return MacKeyboardInputBlocker(on_pause)
    return NullInputBlocker()
